blueprint:
  name: Aqara External Temperature Sensor Calibration
  domain: automation
  description: |
    ## Aqara External Temperature Sensor Calibration (v1.0.0)
    Synchroniseert de lokale temperatuur van één of meer Aqara TRV E1 (lumi.airrtc.agl001) via ZHA
    met een externe temperatuursensor. (Slightly modded to ignore unknown/unavailable states.)

  input:
    external_temperature_sensor:
      name: External Temperature Sensor
      description: De sensor-entity met de kamertemperatuur.
      selector:
        entity:
          domain: sensor
          device_class: temperature

    trv_external_temperature_input:
      name: Aqara TRVZB(s)
      description: De Aqara radiator-thermostaat(ten) (ZHA, lumi.airrtc.agl001) die je wilt updaten.
      selector:
        device:
          multiple: true
          filter:
            - integration: zha
              manufacturer: LUMI
              model: lumi.airrtc.agl001

    cluster_id:
      name: Cluster ID
      description: Cluster ID van de TRV (default 64704 voor Aqara E1).
      default: 64704
      selector:
        number:
          min: 0
          max: 65535
          mode: box

trigger:
  - platform: state
    entity_id: !input external_temperature_sensor

variables:
  ext_sensor: !input external_temperature_sensor
  trv_devices: !input trv_external_temperature_input
  cluster_id_in: !input cluster_id
  # Ronde op 1 decimaal, zoals je eerder had
  ext_temp_value: "{{ states(ext_sensor) | float | round(1) * 100 }}"

condition:
  - not:
      - condition: state
        entity_id: !input external_temperature_sensor
        state: 'unavailable'
  - not:
      - condition: state
        entity_id: !input external_temperature_sensor
        state: 'unknown'

action:
  - repeat:
      for_each: "{{ trv_devices }}"
      sequence:
        - variables:
            cur_dev_id: "{{ repeat.item }}"
            # Haal IEEE uit device identifiers (('zha', 'xx:xx:...'))
            cur_ieee: >-
              {{ (device_attr(cur_dev_id, 'identifiers')
                  | selectattr(0, 'equalto', 'zha') | list | first)[1] }}
        - service: zha.set_zigbee_cluster_attribute
          data:
            ieee: "{{ cur_ieee }}"
            endpoint_id: 1
            cluster_id: "{{ cluster_id_in }}"
            cluster_type: in
            attribute: 0x1392
            manufacturer: 0x115F
            value: "{{ ext_temp_value }}"
mode: single

